kind: ConfigMap
apiVersion: v1
metadata:
  name: portal-django-conf
data:
  HOST: "portal.glauca.digital"
  DJANGO_SETTINGS_MODULE: as207960_portal.settings
  EXTERNAL_URL: "https://portal.glauca.digital"
  SENTRY_ENVIRONMENT: "prod"
  KEYCLOAK_SERVER_URL: "https://sso.as207960.net/"
  KEYCLOAK_REALM: master
  KEYCLOAK_SCOPES: "openid email profile"
  KEYCLOAK_CLIENT_ID: "portal"
  DB_HOST: "cockroachdb"
  DB_NAME: "portal"
  S3_ENDPOINT: "https://s3.as207960.net"
  S3_REGION: "garage"
  S3_BUCKET: "portal-django"
  S3_ACCESS_KEY_ID: "GKb0d16952d5214be2f12b5975"
  S3_CUSTOM_DOMAIN: "portal-django.content.as207960.net"
  STATIC_URL: "https://portal-django.content.as207960.net/"
  MEDIA_URL: "https://portal-django.content.as207960.net/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-django
  labels:
    app: portal
    part: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
      part: django
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: portal
        part: django
    spec:
      initContainers:
        - name: django
          image: as207960/portal:(version)
          imagePullPolicy: Always
          command: ["sh", "-c", "python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py sync-keycloak"]
          envFrom:
            - configMapRef:
                name: portal-django-conf
            - secretRef:
                name: portal-db-creds
              prefix: "DB_"
            - secretRef:
                name: portal-django-secret
            - secretRef:
                name: portal-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: portal-s3
      containers:
        - name: gunicorn
          image: as207960/portal:(version)
          imagePullPolicy: Always
          command: ["gunicorn", "-w", "8", "-b", "[::]:8000", "--forwarded-allow-ips", "*", "--access-logfile", "-", "--log-level=debug", "--timeout=90", "as207960_portal.wsgi:application"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: portal-django-conf
            - secretRef:
                name: portal-db-creds
              prefix: "DB_"
            - secretRef:
                name: portal-django-secret
            - secretRef:
                name: portal-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: portal-s3
---
apiVersion: v1
kind: Service
metadata:
  name: portal-django
  labels:
    app: portal
    part: django
spec:
  selector:
    app: portal
    part: django
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: portal-django
spec:
  podSelector:
    matchLabels:
      app: portal
      part: django
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-ingress
  annotations:
    cert-manager.io/cluster-issuer: "gts"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - portal.glauca.digital
      secretName: portal-tls
  rules:
    - host: portal.glauca.digital
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portal-django
                port:
                  number: 8000
